<?php

trait TRS_Sea
{
  protected $SKL_SP = [
    //村
     "共有者"=>Data::SKL_FM
    ,"狩人"=>Data::SKL_GUARD
    ,"狼憑き"=>Data::SKL_LINEAGE
    ,"容疑者"=>Data::SKL_REALIZED
    ,"獣化病"=>Data::SKL_COUNTER
    ,"陰陽師"=>Data::SKL_ONMYO
    ,"暗殺者"=>Data::SKL_ASSASSIN
    ,"見習い占い師"=>Data::SKL_SEER_FUZZ
    ,"傾奇者"=>Data::SKL_RANDOM_EATEN
    ,"中身占い師"=>Data::SKL_SEER_ID
    ,"巫者"=>Data::SKL_WILD
    ,"狼少年"=>Data::SKL_MISTAKE_SEER
    ,"猫又"=>Data::SKL_CAT
    ,"運命の子"=>Data::SKL_RANDOM_TOLD
    ,"星詠み"=>Data::SKL_SEER_BAND
    ,"交信者"=>Data::SKL_READ_G
    ,"月酔"=>Data::SKL_MISTAKE_MEDI
    ,"月族"=>Data::SKL_MOON
    ,"解呪師"=>Data::SKL_DISPEL
    //裏切り
    ,"悔罪人"=>Data::SKL_TERU
    ,"座敷童"=>Data::SKL_LUNA_MIMIC_FM
    ,"囮人形"=>Data::SKL_LUNA_BLACK
    ,"悟られ狂人"=>Data::SKL_REALIZED
    ,"感応狂人"=>Data::SKL_LUNA_READ_W
    ,"瘴気狂人"=>Data::SKL_NONE
    ,"誘惑者"=>Data::SKL_LUNA_TEMPT_SEA
    ,"狂科学者"=>Data::SKL_MAD
    ,"呪術師"=>Data::SKL_LUNA_ADD_FRY
    ,"月従者"=>Data::SKL_FANATIC_MOON
    //狼
    ,"賢狼"=>Data::SKL_WOLF_MEDI_ROLE
    ,"霊狼"=>Data::SKL_WOLF_MR_READ_G
    ,"大狼"=>Data::SKL_WWOLF_BLACK_G
    ,"群狼"=>Data::SKL_WOLF_PRINCE
    ,"月狼"=>Data::SKL_WOLF_MOON
    //妖魔
    ,"ハムスター人間"=>Data::SKL_FAIRY
    ,"九尾"=>Data::SKL_FRY_ASS_COUNTER
    ,"呪狐"=>Data::SKL_FRY_CURSED
    ,"半妖"=>Data::SKL_FRY_DYING_HALF
    ,"仙狐"=>Data::SKL_FRY_MEDI_ROLE
    ,"コウモリ人間"=>Data::SKL_FRY_WIS
    ,"サトリ"=>Data::SKL_FRY_SEER_ROLE
    ,"瘴狐"=>Data::SKL_FRY_SEAL
    ,"惑狐"=>Data::SKL_FRY_TEMPT
    ,"夜叉"=>Data::SKL_YASHA
    ,'木霊'=>Data::SKL_FRY_COUNTER
    ,'犬神'=>Data::SKL_FRY_CAT
    ,'鏡狐'=>Data::SKL_FRY_ADD_FRY
    //他
    ,"吸血鬼"=>Data::SKL_VAMPIRE_SEA
    ,"眷属"=>Data::SKL_SERVANT
    ,"コレクター"=>Data::SKL_SEE_WILD
    ,"スナッチャー"=>Data::SKL_SEA_NONE
    ,"ギャンブラー"=>Data::SKL_SEA_EXPECT_ALIVE
    ,"グリムリーパー"=>Data::SKL_SEA_EXPECT_DEAD
    ,"レギオン"=>Data::SKL_SEA_EXPECT_WIN
    ,"パナギア"=>Data::SKL_SEA_ADD_FRY
    ,"カロン"=>Data::SKL_SEA_WITCH
    ];
  protected $TM_SP = [
     "贖罪"=>Data::TM_TERU
    ,"吸血"=>Data::TM_VAMPIRE
    ,"深海"=>Data::TM_SEA
    ];
  protected $WTM_SP = [
     "らかな光が降り注ぐ。全ての"=>Data::TM_VILLAGER
    ,"全ての希望を染めつくした。"=>Data::TM_WOLF
    ,"も、人狼も、妖孤でさえも、"=>Data::TM_LOVERS//誤字
    ,"の対立に終止符が打たれたと"=>Data::TM_VAMPIRE
  ];
  protected   $WTM_RP = [
     "の人物が消え失せた時、其処"=>Data::TM_NONE
    ,"の魔が消滅し舞台はついに終"=>Data::TM_VILLAGER
    ,"侵食は進行しついに舞台の全"=>Data::TM_WOLF
    ,"して全ての魔は滅された。た"=>Data::TM_FAIRY
    ,"して魔は舞台の全てを覆い尽"=>Data::TM_FAIRY
    ,"な困難の果てに勝ち残ったの"=>Data::TM_LOVERS
    ,"して舞台は終焉に近づく。誰"=>Data::TM_LWOLF
    ,"の静寂が舞台を包む。立場の"=>Data::TM_PIPER
    ,"はたった独りだけを選んだ。"=>Data::TM_EFB
  ];
}
